import streamlit as st
from google import genai
from google.genai import types

# --- PAGE CONFIG ---
st.set_page_config(page_title="Satyam's AI Assistant", page_icon="🤖", layout="centered")

# Enhanced CSS for high-contrast visibility
st.markdown("""
    <style>
    .stApp { background-color: #EBF0F5; }
    /* Force text inside messages to be clearly dark grey/black */
    .stChatMessage p, .stChatMessage span, .stChatMessage div { 
        color: #1E293B !important; 
    }
    .stChatMessage { border-radius: 15px; margin-bottom: 10px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
    </style>
    """, unsafe_allow_html=True)

st.title("🤖 Satyam's AI Assistant")
st.info("Batch 2024 AI Engineering Project")

# --- SECURE API KEY ---
try:
    API_KEY = st.secrets["GEMINI_API_KEY"]
except:
    API_KEY = "AIzaSyCMpPyLybdthGF71BoRLJfxMSVWTrE6b3k"

client = genai.Client(api_key=API_KEY)
sys_msg = "You are a professional AI assistant built by Satyam, an AI Engineer (2024 batch). Respond briefly and cleanly."

# --- CHAT HISTORY LOGIC ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display the conversation history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        # If an audio response exists for this assistant turn, play it back
        if "audio_bytes" in message:
            st.audio(message["audio_bytes"], format="audio/mp3")

# --- SIDEBAR VOICE CONTROL ---
with st.sidebar:
    st.header("🎙️ Voice Dashboard")
    st.write("Click below to speak to the assistant.")
    
    from streamlit_mic_recorder import mic_recorder
    audio = mic_recorder(
        start_prompt="⏺️ Record Voice",
        stop_prompt="⏹️ Stop & Send",
        key='voice_recorder'
    )
    
    st.write("---")
    if st.button("🗑️ Clear Conversation"):
        st.session_state.messages = []
        # Clear loop checking states on flush
        if 'last_audio_id' in st.session_state:
            del st.session_state['last_audio_id']
        st.rerun()

# --- AUDIO INPUT PROCESSING ---
# Check a unique session flag to make sure we don't process the same audio object twice
if audio and st.session_state.get('last_audio_id') != audio['id']:
    # Store the unique ID of this current recording to prevent the infinite loop
    st.session_state['last_audio_id'] = audio['id']
    
    with st.chat_message("assistant"):
        with st.spinner("Listening to audio and generating response..."):
            try:
                from google.genai.types import Part, GenerateContentConfig
                
                audio_part = Part.from_bytes(
                    data=audio['bytes'],
                    mime_type="audio/wav"
                )
                
                # Request BOTH text and audio output structures back from the Gemini 2.5 endpoint
                config = GenerateContentConfig(
                    response_modalities=["TEXT", "AUDIO"],
                    system_instruction=sys_msg
                )
                
                # Using full gemini-2.5-flash for multimodal audio generation support
                response = client.models.generate_content(
                    model="gemini-2.5-flash", 
                    contents=[audio_part],
                    config=config
                )
                
                full_response = response.text
                
                # Extract the audio bytes generated by Gemini's vocal synthesis engine
                ai_audio_bytes = None
                for part in response.candidates[0].content.parts:
                    if part.inline_data:
                        ai_audio_bytes = part.inline_data.data
                
                # Save data objects to session history safely
                st.session_state.messages.append({"role": "user", "content": "🎤 *Sent a voice message*"})
                
                msg_data = {"role": "assistant", "content": full_response}
                if ai_audio_bytes:
                    msg_data["audio_bytes"] = ai_audio_bytes
                    
                st.session_state.messages.append(msg_data)
                st.rerun()
                
            except Exception as e:
                st.error(f"Audio Processing Error: {e}")

# --- TEXT INPUT HANDLING ---
if prompt := st.chat_input("Ask me anything..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            from google.genai.types import GenerateContentConfig
            config = GenerateContentConfig(
                response_modalities=["TEXT", "AUDIO"],
                system_instruction=sys_msg
            )
            response = client.models.generate_content(
                model="gemini-2.5-flash", 
                contents=prompt,
                config=config
            )
            full_response = response.text
            
            ai_audio_bytes = None
            for part in response.candidates[0].content.parts:
                if part.inline_data:
                    ai_audio_bytes = part.inline_data.data
            
            st.markdown(full_response)
            if ai_audio_bytes:
                st.audio(ai_audio_bytes, format="audio/mp3")
            
    msg_data = {"role": "assistant", "content": full_response}
    if ai_audio_bytes:
        msg_data["audio_bytes"] = ai_audio_bytes
    st.session_state.messages.append(msg_data)
